### ISSUE TITLE
Implement CSW API for the system

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#104]
The [CKAN spatial extension](https://github.com/ckan/ckanext-spatial) does not really expose a general-purpose CSW API, it is only able to expose it from those datasets that were themselves generated from harvesting.

We need to be able to offer a CSW interface to existing EMC datasets.

It is likely possible to configure a [pycsw](https://docs.pycsw.org/en/2.6.1/administration.html#mapping-to-an-existing-repository) instance with custom repository mappings. We may need to set up some DB views for it in order to have a nicer way to map between CKAN's package and package_extra tables.

Additional reference:

- https://github.com/geopython/pycsw/blob/master/pycsw/core/config.py

**Comment by ricardogsilva** [comment]
I'm investigating the possibility to use pycsw with custom repository mappings. In order to be able to integrate pycsw it seems we need a DB VIEW that puts all dataset information in a single row (as opposed to scattered between the `package`, `package_extras` tables).

However, pycsw does not seem to support using a SQL VIEW as the source for its information. I've opened an issue at the pycsw repo:

https://github.com/geopython/pycsw/issues/747

Lets see how this evolves

**Comment by ricardogsilva** [comment]
My proposed PR on pycsw seems to work nicely - need to wrap it up

**Comment by ricardogsilva** [comment]
Still todo is implementing a way to refresh the generated materialized view when relevant.

I need to look into [postgresql's docs on refreshing a materialized view](https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html) - apparently we can do it concurrently too

**Comment by NyakudyaA** [comment]
You can also take a look at https://github.com/sorokine/RefreshAllMaterializedViews
