### ISSUE TITLE
total number of datasets is the same as the number of filtered results

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#116]
When performing a search, the UI reports both the a) total number of datasets and b) the number of results that matched the search filters. The portal currently only shows b) as if it were both things.

As an example:

![image](https://user-images.githubusercontent.com/732010/156741041-502780b4-2283-4b62-aaf3-de2048f4b41c.png)

Above I have an active search filter, which is the geospatial bounding box, and the UI reports both `Total number of datasets: 25` and `25 datasets found`.

**Comment by gubuntu** [comment]
@Mohab25 when closing an issue like this please include a screenshot showing the corrected behaviour

**Comment by Mohab25** [comment]
will provide images soon
