### ISSUE TITLE
RF10, RF11, RF12 implement saved searches

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#137]
As mentioned in [functional requirements](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/wiki/Functional-Requirements) RF10, RF11, RF12, lets implement a way for users to store their dataset searches in such a way as to enable them to reproduce a search later.

Perhaps implementation can simply store a fixed number of past searches (ex: last 10 searches) and the GUI shall offer to apply those?

**Comment by ThiashaV** [comment]
RF10, RF11 and RF12 @Mohab25

**Comment by Jeremy-Prior** [comment]
Saved searches implemented on the staging site:
![SavedSearches](https://user-images.githubusercontent.com/100694811/208626625-b64fe0e7-8b11-43da-a1b3-1ebc200adf69.png)

**Comment by seabilwe** [comment]
@Mohab25, Jeremy and I just realised that the Create Saved Search functionality does not have the option to delete the searches that have been saved.

The Create Saved Search functionality covers RF10, but RF11 and 12 are not accounted for, that is deleting the saved searches
![image](https://user-images.githubusercontent.com/56301949/209096155-128c245a-6cad-4a48-ace7-2531c45c3769.png)

**Comment by Mohab25** [comment]
adding two new buttons, the first is applying the search and the other is delete saved search, note that if you are accessing as a system admin, you can see and delete all other users saved search (RF12).
![delete-saved-search](https://user-images.githubusercontent.com/58084234/209257827-d1b6c6af-4f94-456f-9925-895bc40f7b32.png)

**Comment by Jeremy-Prior** [comment]
R9(sysadmin) can see and delete saved searches from other profiles. 
R9 profile(on the left) displaying the saved searches from a R5 profile (on the right)
![image](https://user-images.githubusercontent.com/100694811/211999976-4eab6f2c-7345-4c5e-8b1c-bd0f60bc2240.png)

**Comment by ThiashaV** [comment]
R2 doesn't have the ability to save searches/ delete searches 
![image](https://user-images.githubusercontent.com/98025261/212264251-5539eba8-ba00-4558-ab79-6fb9ae8b804c.png)

**Comment by ThiashaV** [comment]
@Mohab25 @seabilwe

**Comment by Mohab25** [comment]
with the latest fixes Both R2 and R3 are able to perform searches, re-open if necessary
