### ISSUE TITLE
integrate DOIs into the dataset schema

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#168]
Some datasets that are being imported from the legacy SASDI EMC have a [Digital Object Identifier] (AKA DOI). We need to be able to preserve this information.

[digital Object Identifier]: https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by gubuntu** [comment]
fix as part of #299

**Comment by Mohab25** [comment]
the DOI as it is, is now integrated to the schema, other fields (like metadata record name) can also be treated as unique values,

![Screenshot from 2022-10-26 01-18-34](https://user-images.githubusercontent.com/58084234/197963812-c7f2242b-9307-4f0c-b143-b05fd80d15a2.png)
