### ISSUE TITLE
Add templates for customization of DCPR-related activities

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#179]
Don't forget to show a link to the actual DCPR request in those activities that are relevant

**Comment by gubuntu** [comment]
Please clarify this and link to a requirement and client UI/UX confirmation before coding

**Comment by gubuntu** [comment]
linked to or duplicate of 276?

**Comment by Samweli** [comment]
Not sure about this, it doesn't seem to be linked to the #276

**Comment by gubuntu** [comment]
@Samweli please find out from @ricardogsilva else move to the bottom of the backlog else close

**Comment by Samweli** [comment]
> @Samweli please find out from @ricardogsilva else move to the bottom of the backlog else close

Right, @gubuntu.
