### ISSUE TITLE
Create help section for DCPR and add relevant contents

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#183]
The DCPR section needs a proper help section. The info box on a DCPR request's detail page shall also link to this upcoming help section so that users have a direct way to read some useful docs about DCPR.

Follow a similar approach as was done for the other help pages - _i.e._ make it so that the `bootstrap create pages` command creates this section too.

**Comment by Mohab25** [comment]
this is not completed yet , as per ticket "The info box on a DCPR request's detail page shall also link to this upcoming help section"

**Comment by Mohab25** [comment]
added a link to the dcpr help info box and the dcpr help section.

![dcpr help section-min](https://user-images.githubusercontent.com/58084234/188119505-0895b483-1585-4606-a669-b6d71504a532.gif)
