### ISSUE TITLE
Allow filtering DCPR requests

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#192]
The DCPR request section ought to allow searching for existing request by applying different search filters - that would make it more pleasant for the end-user

**Comment by gubuntu** [comment]
as per feedback, DCPR record filtering needs to occur in the EMC section, so halt work on filtering in the DCPR section. Still commit it so it's not lost. Shift focus to integrating the DCPR search interaction with the EMC as per feedback and mockups

**Comment by Mohab25** [comment]
based on multiple feedback, this issue is moved to #218 , as we are seeking to further integrate DCPR requests and EMC metadata in one search engine.
