### ISSUE TITLE
Add link to the stats section

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#208]
Following the same rationale as discussed in #48, lets add a navigation to the `/stats` endpoint so that the CKAN statistics are shown to logged-in users

**Comment by Fanevanjanahary** [comment]
@ricardogsilva this is already there, _Usage statistics _

![image](https://user-images.githubusercontent.com/12623986/173927193-629eadde-6c3f-4f92-8276-fc2736b96dc0.png)

**Comment by gubuntu** [comment]
There's no content there, is it not fully implemented?

I suggest some communication to establish what stats to show for each of these three RFs, and how they should be represented.
