### ISSUE TITLE
NSIF representative should not be allowed to reject a DCPR request

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#210]
The DCPR workflow should not allow NSIF representatives to reject a DCPR request - according with the official DCPR legislation, the NSIF shall only be allowed to comment on a DCPR request in order to aid the CSI. It is the CSI which should be responsible for the final moderation of a DCPR request

**Comment by gubuntu** [comment]
However, the NSIF should filter out spurious requests such that the CSI gets to review only valid requests

**Comment by Mohab25** [comment]
@Samweli didn't merge yet based on @gubuntu latest comment, is this case being taken care of ?

**Comment by gubuntu** [comment]
As we saw in the demo last Friday, the current behaviour is correct. When the NSIF reviewer Submits, that is effectively an approval and it goes to the CSI for review. If the NSIF 'rejects' the request, the action is to delete it.

**Comment by Samweli** [comment]
@gubuntu @Mohab25 NSIF representative can filter out requests by using "Move back to draft" action, this will ask for modifications to be made on the DCPR request before it is read for a CSI review.

**Comment by gubuntu** [comment]
that also sounds right. So if I understand correctly, options now are
Submit (to CSI)
Delete
Move back to draft

**Comment by Samweli** [comment]
@gubuntu yes those are the currently options, in the PR https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/pull/216 the proposed options are 
Submit (to CSI)
Move back to draft.

The delete/reject option has been removed for the NSIF representative

**Comment by Mohab25** [comment]
@Samweli so as @gubuntu "NSIF should filter out spurious requests" implementation only means adding comments to requests and label it as something spurious ?

**Comment by gubuntu** [comment]
Mohab showed the current behaviour (with Delete option) and Vutomi confirmed it was correct. So I'd say the above three options are correct, but best bring Vutomi into the conversation (and ask him to register on GitHub...)
