### ISSUE TITLE
In Create Dataset screen, I get internal server error when clicking Add Data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#219]
I should get a validation error rather than a server error if there are any missing or invalid fields

**Comment by seabilwe** [comment]
When required fields have not been added, you get a validation error. 
![validation error](https://user-images.githubusercontent.com/56301949/179968364-60ed4ddf-1d33-4cb7-af9d-68685b8d29f5.gif)
