### ISSUE TITLE
Plan UAT

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#224]
testing must occur on the staging site deployed on client infrastructure. 

### Suggestions
- automated testing (unit tests, UI tests, etc) should go as far as possible
- Kartoza staff should do systematic user testing in parallel
- All PSC members and anyone else nominated by Vutomi should have an opportunity to test
  - at least one person in each role
- Basic instructions / help / documentation needs to be in place first
- users should self register then go through the process we would expect in production
- Users should test all functionality they would use in their role in their organisation
- Use the wiki (list of requirements), a shared spreadsheet or other tool to guide testing and gather feedback (pass, fail, comments etc.)
- Feedback should be via existing GitGub issues, new Issues if bugs, else GitHub Discussions (curated by dedicated Kartoza staff)
- deployment process from develop to testing to staging must be clear and well communicated (e.g. weekly 'test failed issues again because fixes have been deployed')
- well before the end of UAT, we must start taggin pre-release versions and deploying to production, aiming for v.1.0 to be signed off, released and launched by the end of the period.

**Comment by gubuntu** [comment]
Thiasha created this form as a draft test https://docs.google.com/forms/d/e/1FAIpQLSedDmNda-Mpsp_ilWE6JrpdI4jvVoqQru9-tlNUJ4Cz497uVA/viewform

**Comment by ThiashaV** [comment]
@gubuntu are we happy with the format of the UAT? if yes, can I close this issue?

**Comment by gubuntu** [comment]
I am, but I don't see the menu items on testing yet and the main Help page should be an intro and catalogue to the rest of the pages. 

Also I think we can close this if the client has approved it, is that the case after Monday's meeting?

**Comment by ThiashaV** [comment]
UAT has been planned and is mostly complete. I am just waiting to add some functional requirements that are still being implemented on the site. The drop-down menu has been implemented and all pages correspond with their google form.
https://docs.google.com/forms/d/1D2UoWRwdrNySdTDsznaF_L6PQXu9FkP-heb8qVHYYTg/edit
![image](https://user-images.githubusercontent.com/98025261/204297279-25896001-9e68-4225-91e2-0117b85d79fc.png)
We are meeting with Vutomi on Wednesday morning to have a dry run for testing
