### ISSUE TITLE
RG08 populate Help, FAQ and About pages

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#225]
These documents need to be populated asap so that initial users can understand enough to conduct testing, then we can iteratively improve and enrich them as we get feedback during the test period.

FAQs particularly should wait until we get a sense of common questions users actually have or ones that we can anticipate.

Note that you should coordinate with @Mohab25 and if necessary @tharanathkartoza to ensure that any content you create persists through updates and upgrades and gets transferred to staging and ultimately production, which is where ongoing content maintenance will take place.

EMC help: https://testing.emc.kartoza.com/pages/help
FAQ: https://testing.emc.kartoza.com/pages/frequently-asked-questions
About: https://testing.emc.kartoza.com/pages/about

**Comment by Mohab25** [comment]
@gubuntu  is this still opened ? the mentioned pages are populated although they may need more info,

**Comment by gubuntu** [comment]
Now that the wysiwyg editor is implemented, @ThiashaV please update the docs with screenshots after figuring out with the team how to handle or convert the current raw markdown format

**Comment by gubuntu** [comment]
@ThiashaV please comment on progress here

**Comment by ThiashaV** [comment]
Documents are updated with screenshots. For now, they are up to date.

**Comment by ThiashaV** [comment]
Help, FAQ and about pages are populated enough for testing to occur. As final functional requirements get added to the site, the documentation will be updated accordingly 
![image](https://user-images.githubusercontent.com/98025261/202167009-eb4dae5e-3728-4478-a779-24abbfdfea6d.png)
![image](https://user-images.githubusercontent.com/98025261/202167038-726122eb-7765-44cf-ae46-e54669c5fdf0.png)
![image](https://user-images.githubusercontent.com/98025261/202167125-c04c8627-fc07-4de1-9355-884135a83a1d.png)
