### ISSUE TITLE
DCPR internal server error

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#227]
When logged in as admin I get an internal server error at https://testing.emc.kartoza.com/dcpr but not when logged out

**Comment by seabilwe** [comment]
DCPR loads okay when logged in and out of the site
![dcpr](https://user-images.githubusercontent.com/56301949/179967970-7f72a85e-5ed2-4bc2-944b-7b55b01f4bb5.gif)
