### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#230]
When you try resetting your password, the request to reset it does not go through. I haven't received any emails and the page goes back to the home screen.

**Comment by Mohab25** [comment]
this is related to enable SMTP service with CKAN, @tharanathkartoza i think we have an SMTP service with the docker container named ckan-mailer, i've tried to use without luck, will probably will test it again, any help here would be appreciated,

**Comment by Mohab25** [comment]
@gubuntu sending emails via CKAN is a matter of changing configuration, this is on devops team court for SMTP config, the following screenshot was taken when i was working with the xml files upload with an external SMTP provider 

![Screenshot from 2022-08-28 22-46-36](https://user-images.githubusercontent.com/58084234/201191373-2cd968b2-0f3d-4e7b-aaea-ebfcf49d80b4.png)

**Comment by gubuntu** [comment]
@ntobe-nyuswa @vutomim please request SMTP service details and credentials from OCIO so we can get the system to send emails for things like password resets, registration and notifications.

**Comment by EliVolsch** [comment]
When trying to reset my password its seems the site now displays error 502. The request did not complete and I did not receive and email either.
![image](https://user-images.githubusercontent.com/107027990/216546601-e478a615-7af0-4f7b-993e-26967cfbe0c6.png)
