### ISSUE TITLE
Temporal range filter

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#231]
I get an internal server error ( ERROR[500]) when I set the temporal range. It's also not very user-friendly to change the date/year

**Comment by Fanevanjanahary** [comment]
Hi @ThiashaV please can you add a gif screen? Thank you

**Comment by ThiashaV** [comment]
It seems to be working now but yesterday it didn't. @Fanevanjanahary can I close the issue?

**Comment by Fanevanjanahary** [comment]
you can close @ThiashaV, thank you.
