### ISSUE TITLE
Standardise language to UK English and not American English

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#232]
The site is written mostly written in American English, South Africa uses UK English as a standard. Words like 'Organization' must change to 'Organisation'
![image](https://user-images.githubusercontent.com/56301949/178258298-890c4caf-6722-4ee8-b5e3-497d0d2f3500.png)

**Comment by Jeremy-Prior** [comment]
The "Organisation Management and Membership" page's title had the American spelling in the title. I edited the title but the URL still contains the American spelling and I am unsure if that can be changed. 
![image](https://user-images.githubusercontent.com/100694811/201094272-a527ddd0-cec1-47b3-9651-2896c8c9c7b1.png)

**Comment by Jeremy-Prior** [comment]
I'm editing pages to correct to British English spelling.

The "Organisation Management and Membership" page's title had the American spelling in the title. I edited the title but the URL still contains the American spelling and I am unsure if that can be changed. 
![image](https://user-images.githubusercontent.com/100694811/201094272-a527ddd0-cec1-47b3-9651-2896c8c9c7b1.png)

**Comment by Jeremy-Prior** [comment]
Spelling has been changed
