### ISSUE TITLE
Changing 'Dataset' to 'Metadata Record'

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#234]
Since the platform is based on providing metadata to the public, it would suffice to give a more relevant description of what content is provided. I understand CKAN provides 'Dataset' and as title natively.
 
![image](https://user-images.githubusercontent.com/56301949/178262144-deed744a-a77d-4ec1-bcd9-099e00200b64.png)

**Comment by seabilwe** [comment]
@Fanevanjanahary most of the site has been replaced by Metadata record.

Looking through the different pages, I see that there are some areas of the site that have not changed:

1. When clicking on **Add metadata record** - there is still **create dataset**
![metadata-record1](https://user-images.githubusercontent.com/56301949/189652027-f39ead4a-bcea-447b-a2ae-99d15a43007e.gif)

2. When navigating to Profile, **Dataset** is still used instead of **Metadata record**
![metadata-record2](https://user-images.githubusercontent.com/56301949/189652219-3e66e576-34d2-46a7-ada3-397ef52e6546.gif)

I'm not sure if it will be possible, but when you navigate to Organisations, the number of metadata records shows for example 38 Datasets instead of 38 Metadata records.
![2022-09-12_14-17](https://user-images.githubusercontent.com/56301949/189652771-72249cef-2451-42c4-b47e-0547642ba27a.png)
![2022-09-12_14-18](https://user-images.githubusercontent.com/56301949/189652783-15198405-eed1-40eb-9a13-ac5634f181d1.png)
![2022-09-12_14-18_1](https://user-images.githubusercontent.com/56301949/189652792-cfe31bc1-f92e-4308-be31-0e65ac7bdb0b.png)

**Comment by Fanevanjanahary** [comment]
Hi, @seabilwe Can you please review this?

**Comment by seabilwe** [comment]
@Fanevanjanahary I am getting this error when clicking on create metadata record. So far I am not seeing any changes on the site.

![metadata-record4](https://user-images.githubusercontent.com/56301949/189896858-968b377a-8e46-47e0-ba2e-0d4db574cc1c.gif)
 record

**Comment by Fanevanjanahary** [comment]
Sorry @seabilwe,  it's not deployed yet. You can check it in an hour or some

**Comment by seabilwe** [comment]
Sure

**Comment by gubuntu** [comment]
Don't forget to handle plurals properly too. e.g. I saw in one of your screenshots 'number of metadata record: 11'. Should be 'records'.

Wherever 'data sets' was plural, make 'metadata records'

**Comment by seabilwe** [comment]
Dataset(s) replaced with Metadata Record(s)
![image](https://user-images.githubusercontent.com/56301949/191475952-77eb1a1a-4168-4538-9edb-490d1cdce56a.png)
![image](https://user-images.githubusercontent.com/56301949/191476108-02a86ef4-8be8-4ab8-8ea0-df57b6677216.png)
![image](https://user-images.githubusercontent.com/56301949/191476401-99ef63b9-40b7-441b-965b-51aa1a2d0270.png)
![image](https://user-images.githubusercontent.com/56301949/191476731-178a7b44-8ae3-4380-a974-8d19f8ca1057.png)

**Comment by Fanevanjanahary** [comment]
Hi @seabilwe  

On the organization page, if the metadata record number is one it removes the (s) like this 

![image](https://user-images.githubusercontent.com/12623986/191681173-2fdd47c4-239c-444d-bfe1-ef986b97f05b.png)

We can't add (s) in this since it's the tab for the dataset's information itself 
![image](https://user-images.githubusercontent.com/56301949/191476108-02a86ef4-8be8-4ab8-8ea0-df57b6677216.png) 

It is better to have the same function as on the organization for the rest of the page. What do you think?

**Comment by seabilwe** [comment]
Hi @Fanevanjanahary, it makes sense for Metadata records to be written in singular form (i.e., metadata record) if there is only one record in the organisation. And yes, if it is just the dataset itself, you can't include the 's'.  

I agree we can have the same function for the rest of the page

**Comment by Jeremy-Prior** [comment]
Metadata Record has replaced Dataset across the site.
The plurality of Metadata Record(s) correctly changes according to the number of records:
![2_NoRecords](https://user-images.githubusercontent.com/100694811/202226794-b6c3c0ee-f006-4a5e-a3ae-6512876e674a.png)
![1_OneRecord](https://user-images.githubusercontent.com/100694811/202226861-3548df19-c332-4907-b841-dc682b3b1ecb.png)

The only place where Metadata Record hasn't replaced Dataset is the browser tab label when a user clicks on "add metadata record":
![3_TabLabel](https://user-images.githubusercontent.com/100694811/202227925-97360af3-1fa8-41e8-8aaf-786adf79ee73.png)

**Comment by Jeremy-Prior** [comment]
Fixed
![4_fixed](https://user-images.githubusercontent.com/100694811/203059589-260d5ddf-6314-423b-94d0-5dd7be658395.png)

**Comment by Jeremy-Prior** [comment]
@Fanevanjanahary Apologies for reopening this but I found some other instances on the site where 'Dataset' needs to be changed to 'Metadata Record' during versioning testing.

- When updating a metadata record (select a record, and then click "Manage") the button to update the record still says "Update Dataset", I suggest "Update Record" instead. It also says "dataset" in the paragraph which should be changed to "metadata record":
![5_DatasetOnUpdatePage](https://user-images.githubusercontent.com/100694811/203494785-a8f0e2ac-a43a-4a50-9573-594ce9675a58.png)

- On a metadata record with no associated data the description still contains "dataset":
![6_DatasetOnEmptyRecord](https://user-images.githubusercontent.com/100694811/203495222-a68acd8c-f8e7-40e5-af76-ca197b4cdc5b.png)

- On a record that was deleted/no longer exists it still says "dataset". This was from record https://testing.emc.kartoza.com/dataset/resources/testing_versioning_pt2_v_7:
![7_DatasetOnNullRecord](https://user-images.githubusercontent.com/100694811/203495396-8e5885d1-4485-4d3a-a548-88b268ee20be.png)

**Comment by Mohab25** [comment]
![Screenshot from 2022-11-29 03-29-32](https://user-images.githubusercontent.com/58084234/204416455-d7e9dc96-1fd7-4a86-846c-fa1c76183277.png)
![Screenshot from 2022-11-29 03-30-28](https://user-images.githubusercontent.com/58084234/204416458-dc42f398-05c2-4532-8951-8a7bd138b689.png)
![Screenshot from 2022-11-29 03-30-34](https://user-images.githubusercontent.com/58084234/204416462-5e389a35-78a2-42e0-975d-fdeec77fc910.png)

**Comment by Jeremy-Prior** [comment]
Final three instances changed on testing site.
