### ISSUE TITLE
Expand filter after see more 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#237]
For now, in the datasets filter when we click on _See more organizations_ for example, the page will reload, and the filter accordion doesn't open. It should stay expand.

**Comment by seabilwe** [comment]
The filter accordion stays open after page reload
![ticket-237](https://user-images.githubusercontent.com/56301949/185379535-56797384-a8d6-488a-acc3-f3ef26b1f828.gif)
