### ISSUE TITLE
enable adding media to pages

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#239]
We need to add screenshots, screencasts etc. to Help and other pages, which is currently not possible.

**Comment by Mohab25** [comment]
we are currently using ckanext-pages to create help, faq ..etc, the plugin comes with a configuration setting that enables editing in a  WYSIWYG editor, images, videos and other types of media can be added, @tharanathkartoza please add the following to ckan.ini file for both testing/ staging instances.  `ckanext.pages.editor = ckeditor`

![WYSIWYG editor](https://user-images.githubusercontent.com/58084234/188203667-5e361c86-02a5-4055-8a37-72621d41f6d9.png)



![media added to a page](https://user-images.githubusercontent.com/58084234/188203526-8147717a-9f52-48ec-80c0-6e653962d0fa.png)

**Comment by ThiashaV** [comment]
Uploading media enabled 
![image](https://user-images.githubusercontent.com/98025261/202169051-65e63641-1974-42c8-8165-1b0e5ad1800b.png)
