### ISSUE TITLE
work new logos into the UI

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#240]
The final svg version of the thematic logos that Maria designed must appear on the site wherever SADI and GGIM themes are mentioned - in the filters and in the presentation of metadata records.

**Comment by Fanevanjanahary** [comment]
Hi @gubuntu the sasdi logos from Maria are missing Wetlands, for the moment I used one of the existing ones. 

Please where can I find GGIM? cc @Mohab25
