### ISSUE TITLE
Date selector allows for too many digits

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#242]
When you manually input a date the YYYY field allows entering 6 digits before switching to MM field. See image. 
![EMC_DateSelection](https://user-images.githubusercontent.com/107027990/178702412-a1c35259-f512-414f-b25b-b074d5eb7db2.png)

**Comment by ThiashaV** [comment]
After entering 4 digits for the year, it moves to month. 
![image](https://user-images.githubusercontent.com/98025261/202168598-ae6db5b7-fcbb-49fa-86b8-e351cc1904f3.png)
