### ISSUE TITLE
Bug in datasets page 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#245]
Hi @Mohab25, 

Testing your PR now, and got error `ckan.logic.NotAuthorized` it is from ` line 18, in block 'package_search_results_list'`

Update: testing with admin, it works, you may need to check if the user is authorized

**Comment by Mohab25** [comment]
@Fanevanjanahary is the tester you're using have a dcpr requests view capabilities?
