### ISSUE TITLE
When Logged out navigating to dataset produces AttributeError

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#254]
When not logged in navigating to the dataset page produces the following error: AttributeError: 'NoneType' object has no attribute 'id'
![EMC_DataseterrorLogout](https://user-images.githubusercontent.com/107027990/179979920-7278e597-6159-47c4-8984-bd53546ddf02.png)

**Comment by EliVolsch** [comment]
This issue seems to be resolved and should be closed.

**Comment by gubuntu** [comment]
you can close an issue yourself, especially if you reported it
