### ISSUE TITLE
Combining any number of features in RF08 produces a 0 result

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#256]
RF08 - Combine several search filters in order to refine search operations. The system shall allow performing a logical addition of the search filters discussed on requirements RF02, RF03, RF04, RF05, RF06 and RF07. 

![EMC_FilterFunctionality](https://user-images.githubusercontent.com/107027990/180977632-86a50711-c378-4168-8d69-38fd15474646.png)
In example I selected more than one organization and it returned a 0 records found result. This also applies to combining, date and organization, and keyword and organization.

**Comment by gubuntu** [comment]
Different filter groups should be combined with AND

Filters within the same group should be combined with OR

**Comment by Jeremy-Prior** [comment]
Combining multiple filters returns all Metadata records related to the search filters.
![MultipleFilters](https://user-images.githubusercontent.com/100694811/202461476-c6ac3c02-5384-46f1-8437-33b86a4d45f4.gif)
