### ISSUE TITLE
RG05 Portal must implement basic SEO techniques, such that it is promoted by Web search engines

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#269]

**Comment by Mohab25** [comment]
@gubuntu can we move this to the next phase, it's much more of a stabilization task ?

**Comment by Jeremy-Prior** [comment]
Reading through https://developers.google.com/search/docs/fundamentals/get-on-google?hl=en, the first SEO test is the '_site:example.com' test.
The testing site appears if you use this test:
![issue269_1](https://user-images.githubusercontent.com/100694811/225557164-814f3351-6270-4140-ba0c-ea9dceb5049c.png)
The staging site does not:
![issue269_2](https://user-images.githubusercontent.com/100694811/225557877-9360abf4-6116-4d3b-b3dc-044ea6859561.png)
Even simple searching for the URL does not return the site as a result (this was tried on Google, DuckDuckGo and Bing all with similar results):
![issue269_3](https://user-images.githubusercontent.com/100694811/225558529-0c4384fd-a596-473a-a87f-0b4dc18d820a.png)
