### ISSUE TITLE
RG09 Actions taken on the portal shall be auditable

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#270]
The system shall be able to track data editing operations and provide an audit trail that specifies which user performed the modification and on which date.

**Comment by gubuntu** [comment]
@Mohab25 or @Samweli, @ricardo marked this as partly implemented in https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/wiki/General-Requirements. Please establish what remains to complete it and describe that in the OP

**Comment by Mohab25** [comment]
@gubuntu i've referred to the requirements document, NC, and the wiki to gain more information about what should go to the Audit trial, should it be sent to someone timely ..etc. but nothing more than what is described here, now CKAN stores every activity in the site (package creation, deletion, update,  organization creation..etc. ) along together with the user, the timestamp and the data which describes in detail the action taken to make a change, what else should be done from here ?, would for example providing a UI to the database (pg admin) is sufficient ?

**Comment by gubuntu** [comment]
I think a query or something demonstrating the history of a record, posted here, should be sufficient for now

**Comment by Mohab25** [comment]
the following image illustrates  the result of the following query, it shows the timestamp and the data of a certain activity:
`select timestamp, data from activity;`

![Screenshot from 2022-09-16 13-52-35](https://user-images.githubusercontent.com/58084234/190633363-c7784f36-f97b-4256-9909-545e81e3bf9e.png)
