### ISSUE TITLE
RF02 Search for existing metadata records or DCPR records by text

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#271]
Text searches shall allow filtering of existing catalogue records by a number of their existing textual properties. This shall include: 

- [x] Title
- [x] Abstract
- [x] Unique Identifier (also referred to as record search).

**Comment by gubuntu** [comment]
@Mohab25 or @Samweli, @ricardo marked this as partly implemented in https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/wiki/Functional-Requirements. Please establish what remains to complete it and describe that in the OP

**Comment by Samweli** [comment]
@gubuntu @Mohab25  the current Text searches cover the Title and Abstract, what remains is the Unique Identifier inclusion.

**Comment by gubuntu** [comment]
related to #272

**Comment by Mohab25** [comment]
as there isn't feedback, wet took the path of having both the doi, and the metadata record name (name in CKAN terms, which is pretty much the url of the record) to be the unique identifiers, both of these are searchable via the search form


![Screenshot from 2022-10-26 01-18-34](https://user-images.githubusercontent.com/58084234/197964732-b3c56cbf-9f0e-4816-80f3-71082ba94a53.png)
