### ISSUE TITLE
Resolve unique identifier and implement if necessary

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#272]
RF02 (#271) refers to a unique identifer in search.

Clarity is required as to what this unique identifier is. 

The back-end has a built-in serial integer unique identifer - is that what it meant? I doubt users will search for that. 

@ntobe-nyuswa can you provide any insight?

**Comment by vutomim** [comment]
Please send the database ERD and dictionary so that we can be able to check if it has been correctly dealt with in the back-end.

**Comment by gubuntu** [comment]
@Mohab25 @ntobe-nyuswa please resolve asap

**Comment by Mohab25** [comment]
@ntobe-nyuswa already sent the database ERD, please tag me in your comments whenever this is ready

**Comment by vutomim** [comment]
@Mohab25 it is very difficult to make sense of what you sent. Was hoping for a simple ERD with a dictionary that will show the name of the Table, attributes, the relationship between tables and the description of attributes. Let's discuss the item on Friday. 

What we needed for the requirement is that as a publisher, you need to have a unique identifier for your record which you can always use to call for that record if you want to view or make changes. This record should also enable users if they have that UID to use it to search.

**Comment by gubuntu** [comment]
The unique ID could be a URI (e.g. a unique url, which is in place) or a unique database primary key or other field (all tables have unique ID primary fields). We were hoping for some guidance or specification on what is required as a unique ID that will also be used in searches. 

We could simply index the URI or record key (and expose the latter) to be used in searches to satisfy this and #271

**Comment by Mohab25** [comment]
for further comment please refer to #271
