### ISSUE TITLE
Update publish page UI as the old version

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#277]
- [ ] The new Publish page should be laid out like the ‘old version’ DCPR page.
- [ ] The three options should be ‘Capture Metadata’, ‘Upload Metadata’, and ‘Harvest metadata’

 It must have no DCPR content. The reference to that old DCPR slide was only for the layout. What you have put in buttons must be put into blocks with text like those below and the introductory text must be about creating or publishing metadata

**Comment by Fanevanjanahary** [comment]
@gubuntu 
![image](https://user-images.githubusercontent.com/12623986/184330675-4e297a71-aced-45cf-8ff6-2bacc936b38b.png)

**Comment by vutomim** [comment]
> * [ ]  The new Publish page should be laid out like the ‘old version’ DCPR page.
> * [ ]  The three options should be ‘Capture Metadata’, ‘Upload Metadata’, and ‘Harvest metadata’

@gubuntu, @Fanevanjanahary and @Mohab25 this is a misinterpretation of our statements. The publish page should be separated from the DCPR page. The three buttons Add dataset, upload xml and Harvesting should be left on Publish page with some info on what EMC is about, and explanation of how each button work and can follow DCPR design page (see sample page below. 

![image](https://user-images.githubusercontent.com/40568449/184342434-b1fc611b-2e93-4166-ac36-f46b34d4f2d6.png)

**Comment by Fanevanjanahary** [comment]
@vutomim I'm sorry for the misinterpretation, Gavin had already brought that to my attention and I'm addressing it according to your comment above.

**Comment by Jeremy-Prior** [comment]
Publish Page matches the sample page provided:
![image](https://user-images.githubusercontent.com/100694811/202644693-f0db99c8-b6af-4873-b297-3c016b88d141.png)
