### ISSUE TITLE
Carousel is too deep

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#281]
I think the carousel height should be reduced so that the text is vertically centred on it and so that the row of SASDI icons is more likely to be visible without scrolling

<img width="1607" alt="Screenshot 2022-08-12 at 08 20 47" src="https://user-images.githubusercontent.com/496911/184296212-db1652ae-91db-447a-bcc1-b172f5bdb616.png">

**Comment by Jeremy-Prior** [comment]
Carousel height reduced and SASDI icons visible without scrolling:
![Carousel](https://user-images.githubusercontent.com/100694811/202462599-2bb3b687-3aa9-49fd-ad6b-d0d2f6afb0e1.png)
