### ISSUE TITLE
Zero Division Error when clicking on any of the filters

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#285]
When clicking on the filters in the filter tree, a ZeroDivionError appears.

 When refreshing the page, one can click on a filter but, if you click on another filter, the error appears again.
![zero-division-error](https://user-images.githubusercontent.com/56301949/185381862-006ee293-c10c-49ea-bae8-4042c7b99d65.gif)

**Comment by ThiashaV** [comment]
Multiple filters have been selected without any Zero Division Errors. additionally, no errors when refreshing and selecting another filter
![image](https://user-images.githubusercontent.com/98025261/202170992-3c7bb34b-eee3-42dd-8951-5f83cb6b7ab7.png)
