### ISSUE TITLE
Download xml file got an error FileNotFoundError

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#291]
When downloading the data source file in [https://testing.emc.kartoza.com/dataset/sp-townships](https://testing.emc.kartoza.com/dataset/sp-townships)  it gets an error `FileNotFoundError`  

![image](https://user-images.githubusercontent.com/12623986/188381904-84c0ed73-6269-4d0c-8e99-1cc17ce9a19e.png)

**Comment by Mohab25** [comment]
to add more context, this appears to happen when resources are stored locally -something that we shouldn't do as @gubuntu previously stated- one of these resources causes this error named "Sp-Townships" found in a dataset with the same name, after trying to download few other resources with other datasets, it seems the download button works correctly when the resource is not stored with the testing site ckan instance (few screenshots below), i'm not sure if we can generalize this as an issue with the download button, i assume we can show a more graceful message instead trying other approaches (other suggestions are welcomed),
example 1: the "September Means Of Reference Crop Evaporation evaporation-mm-fao-penman-monteith-equivalent"  is a WMS resource found in "September Means Of Reference Crop Evaporation (mm) Fao Penman-Monteith Equivalent" dataset, once you click download it takes you to an xml file stored in this url "https://spatialdata.saeon.ac.za:8082/geoserver/BEEH_grid/wms#penman09" 

![correct download behavior example-1](https://user-images.githubusercontent.com/58084234/187769203-91ae6577-2a5f-4493-85e8-87069ff1c72d.png)
![correct download behavior example-1](https://user-images.githubusercontent.com/58084234/187769202-a9d5efbd-f4a5-46af-95d2-79987d97839a.png)

example 2:  the "[Seasonal total rainfall (mm per 3-month...](https://testing.emc.kartoza.com/dataset/7-seasonal-total-rainfall-mm-per-3-month-season-change-from-the-90-percentile-projected-for-2036-206/resource/db85547b-f481-4ab4-b9b8-7b23744717a0)" is an image resource can be found within "Seasonal total rainfall (mm per 3-month season) change from the 90% percentile projected for 2036-2065, relative to present (1976 - 2005), for SON season under the RCP 4.5 pathway" dataset, if you pressed download it takes you to a png stored with in http://media.dirisa.org/inventory/archive/multi/cc_atlas/fig16a.png

### example about the incorrect behavior:
SP_SCHEME_UNITS is an xml file attached with the "sp_Scheme_units" dataset, and stored in the testing site ckan instance, if you pressed  download it will show the error (which will show internal server error instead when debug mode = False)

![file not found error](https://user-images.githubusercontent.com/58084234/187770828-3e7f3b0d-fc67-4a0a-965d-4a85b87dcc7d.png)

**Comment by gubuntu** [comment]
@Fanevanjanahary please update op with a screenshot of the page where this button / option is

'source' could be ambiguous.

- If a metadata file was uploaded or harvested, is that the source and is it persisted locally?
- only if it was harvested or migrated will there possibly be a remotely accessible source
- If a record was captured via the web UI there is no local xml file, right? But the system (CKAN or pycsw) should be able to generate one for download

I would say 'download xml' should ONLY download local (generated) ISO (SANSA1878) XML and that nothing else should be downloadable from this platform

**Comment by Mohab25** [comment]
@Fanevanjanahary could you please try this again (uploading files to the testing site and download them), after tharanath adjustments, it should work as the volume is not dropping the files from storage folder.

**Comment by gubuntu** [comment]
this is related to #235. The only downloadable file should be the metadata xml file. 

There should be no resource files on the site (#379)
