### ISSUE TITLE
re-run migration

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#299]
Populate the staging instance by running a new migration of legacy data, incorporating any feedback received and mapping to all the new SANSA 1878 fields, improving organisation setup and mapping etc. 

Be prepared to do this a couple of times during September (UAT) if there is feedback on legacy data migration issues. 

For the first production release, run a final migration to seed it. Thereafter users will edit and maintain.

**Comment by Mohab25** [comment]
@gubuntu sizing here depends on reaching a final resolution of SANS1879, will be back to this shortly after checking with the team.

**Comment by Mohab25** [comment]
@gubuntu sizing here depends on reaching a final resolution of SANS1879, will be back to this shortly after checking with the team.

**Comment by gubuntu** [comment]
also check that #320 is resolved

**Comment by gubuntu** [comment]
We should be able to do a better job of populating the organisation field during the migration surely. All or most records in the current system are assigned to an org. It will be a big effort for the NSIF to manually do this

![Screenshot 2023-02-22 at 17 28 19](https://user-images.githubusercontent.com/496911/220671052-4e03b652-762a-4719-8d3c-ddc423e120a1.png) from http://www.sasdi.net/search.aspx
