### ISSUE TITLE
Clarify and document CRUD behaviour and version management

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#300]
'Version' here refers to 'version of a metadata document (record) in the EMC'. Version in any other sense (data set version, metadata standard version etc.) is out of scope of this project - how these are managed is up to the custodians.

There is no mention of 'version' or 'versioning' in the ToR nor Requirements document. Therefore there is no official scope for it in the EMC project and any substantial version-related requirements or work should be handled under a variation order. 

However, the topic of versioning has been raised in a stakeholder workshop and project progress meetings.  

We should be clear about and document what currently happens in the following circumstances. A Variation order could cover development of different or additional behaviour:

- When a record is _edited via the web UI_ (form) is any diff or version created or are previous values simply overwritten?
- When a record with the same title / name / identifier as an existing record is _uploaded_, what happens?
  - perhaps the user should be asked if it is a duplicate (in which case disregard) or if it represents a new version.
  - if it is a new version (e.g. the custodian does a new batch upload each year) then does the same behaviour apply as for a form update?
- Same as above but for _harvesting_

**Comment by Mohab25** [comment]
the current versioning behavior after pull #316 is whenever there is an update on the version field "Dataset version", a new metadata record would be created,  the title of this  record is the same as the original one + the version, this isn't the default behavior of CKAN in which the new updates override the original one (both reflected in the UI and the database), however, a sprint planning meeting took place in September 16th- 2022, in which @vutomim gave more clarification to the versioning behavior, whenever there is a record approved, submitted and stored in the system, that record shouldn't be changed (overrided) under any circumstances, if there is a change by any authorized party, a new metadata record should be created with  a new version, keeping that last one stored and untouched,  with this in mind, the default CKAN update functionality should be completely changed for any step beyond DCPR approval.
waiting for @vutomim to confirm/ reject and further this interpretation.    
@Samweli please take notes, this might affect your work.

**Comment by vutomim** [comment]
> the current versioning behavior after pull #316 is whenever there is an update on the version field "Dataset version", a new metadata record would be created, the title of this record is the same as the original one + the version, this isn't the default behavior of CKAN in which the new updates override the original one (both reflected in the UI and the database), however, a sprint planning meeting took place in September 16th- 2022, in which @vutomim gave more clarification to the versioning behavior, whenever there is a record approved, submitted and stored in the system, that record shouldn't be changed (overrided) under any circumstances, if there is a change by any authorized party, a new metadata record should be created with a new version, keeping that last one stored and untouched, with this in mind, the default CKAN update functionality should be completely changed for any step beyond DCPR approval. waiting for @vutomim to confirm/ reject and further this interpretation. @Samweli please take notes, this might affect your work.

**Comment by vutomim** [comment]
@Mohab25 the interpretation is correct

**Comment by Jeremy-Prior** [comment]
- Changes made to a metadata record by any authorized party result in a new metadata record being created with a new version while an unchanged version of the previous version is stored:
![MetadataVersions](https://user-images.githubusercontent.com/100694811/203029600-f3d1ce9e-03a0-455d-8e6e-389657ebface.png)

- When a record with the same name is uploaded, an error pops us saying that the URL is already in use and a user cannot move forward until a new name is provided:
![SameName](https://user-images.githubusercontent.com/100694811/203026709-4afbc741-2e26-4a14-8970-c1e5c8882705.png)

- Unable to confirm for harvesting:
![Harvester](https://user-images.githubusercontent.com/100694811/203028694-4ff2f12f-44ff-4bc0-bd42-1285418ab728.gif)

**Comment by Jeremy-Prior** [comment]
- When a record is edited via the web UI (form) is any diff or version created or are previous values simply overwritten?
The latest behaviour of the system appears to append to/overwrite the previous values of the record:
![issue300_1](https://user-images.githubusercontent.com/100694811/225588830-95af2b40-1768-43a3-b21c-c55f9b2b2ebf.png)

- When a record with the same title / name / identifier as an existing record is uploaded, what happens?
The system now implements unique identifiers (i.e. a string of characters added to the title) for each record created. This means that records with the same name can be created and can be differentiated from one another using the fields in the Metadata records:
Two records with the the exact same values but with different unique identifiers:
https://catalogue-staging.sasdi.gov.za/dataset/example-title-for-rf24-b37c577e-d5b8-4e8d-89f6-cf3cb023a7db
https://catalogue-staging.sasdi.gov.za/dataset/example-title-for-rf24-8ce506f8-ec6c-4cdf-b304-ebd00b8ac046

- Same as above but for harvesting
Same behaviour as with editing a metadata record:
![issue300_2](https://user-images.githubusercontent.com/100694811/225592342-07297575-2f91-444a-8265-aee11431ff33.png)

Harvesters can be created with the same  title / name / identifier as an existing harvester:
![issue300_3](https://user-images.githubusercontent.com/100694811/225592538-03f320f3-f852-4860-9e11-db8240f631fe.png)
