### ISSUE TITLE
When viewing My Datasets from dashboard produces following error:

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#304]
When navigating from dashboard to my datasets the following error was displayed:

![MyDatasets error 08-57](https://user-images.githubusercontent.com/107027990/188811201-770b502c-099a-4980-8663-38a5b15a25a3.png)

**Comment by ThiashaV** [comment]
The same error occurs when trying to view your profile 
![image](https://user-images.githubusercontent.com/98025261/188850779-4fbb67be-390c-449b-b1e0-74fbb4144de9.png)

**Comment by EliVolsch** [comment]
This issue has been fixed
