### ISSUE TITLE
Remove 'z' from Organization and replace with 's'

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#311]
Currently, Organization is written with 'z', it must be changed to Organisation.

Following the enhancement ticket: #232 

![image](https://user-images.githubusercontent.com/56301949/189653714-5f243617-a990-46fe-b600-c25ed14b4201.png)

**Comment by Jeremy-Prior** [comment]
I have been through the site multiple times and all of the spelling appears to have been changed from the American Spelling with 'z' to the British Spelling with 's'.
![ZtoS](https://user-images.githubusercontent.com/100694811/202145484-6a65d1d2-07e9-45e0-bcf7-b848c8fc162d.png)
