### ISSUE TITLE
Got error while add new metadata record 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#313]
It is an  `KeyError: 'id'`  form `form_snippets/custom_select_field` in new dataset page

![image](https://user-images.githubusercontent.com/12623986/190083351-841a6140-7c21-4e5e-b1c2-066ee36eae30.png)

**Comment by Mohab25** [comment]
fixed with #316
![Screenshot from 2022-09-20 10-22-50](https://user-images.githubusercontent.com/58084234/191206722-1e1b28fe-884a-4e25-bee5-7f5a9301720d.png)

**Comment by Jeremy-Prior** [comment]
No issues when adding new metadata records. Multiple metadata records have been added during testing.
![AddMetadataRecord](https://user-images.githubusercontent.com/100694811/201692616-2e60c0b2-6214-4a25-bfa7-7b0068fcc758.gif)
