### ISSUE TITLE
Format the json data for dataset when the required SANS 1878 fields are empty. 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#320]
The data before July doesn't work correctly since some required SANSA 1878 fields are empty. After an update and filling empty fields, it solves issue #310 and lineage field bugs

**Comment by gubuntu** [comment]
This is a pre-requisite for #299

**Comment by Mohab25** [comment]
@Fanevanjanahary after running database migrations couple of times, it seems this issue is resolved, please re-open otherwise.
