### ISSUE TITLE
Images Missing in Help Page

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#334]
@Mohab25 @tharanathkartoza cc @ThiashaV 

Most of the images on the Help page are missing. 

If they cannot be recovered, @ThiashaV can you forward them to me, and then I can add them, while I am busy with the UAT.
![missing-images](https://user-images.githubusercontent.com/56301949/194306394-2eeec980-21e6-4b36-82ca-cfe9e1ef3ff4.gif)

**Comment by gubuntu** [comment]
why are the images missing? All this static content must be protected and maintained even when the site is redeployed. Preferably retrieve and fix the images. the last resort is to re-do them.

**Comment by ThiashaV** [comment]
Images are missing from all help pages on the testing site 
![image](https://user-images.githubusercontent.com/98025261/204464721-dbd88fbc-9110-43d5-ba8b-a69178b62628.png)

@tharanathkartoza @Mohab25

**Comment by ThiashaV** [comment]
resolved:
![image](https://user-images.githubusercontent.com/98025261/204505502-b3a6ab2d-17d2-4513-b389-312d36bd1f9c.png)
