### ISSUE TITLE
Enable user feedback tool

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#335]
In an early iteration @ricardogsilva had the Crisp chat running as per https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/blob/d640fc2df2802e38729458b3f201a846d3958591/README.md#user-feedback.

Please include in the orchestration on testing, staging and production else identify and implement an alternative feedback mechanism. It is essential during UAT and for ongoing support.

**Comment by Mohab25** [comment]
CRISP is used for interaction, it provides messaging capabilities, files attachments, mailing, and few other capabilities.

**Comment by ThiashaV** [comment]
CRISP is running.
![Uploading image.png…]()
