### ISSUE TITLE
The 'Add metadata record' button is not available in organisations

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#337]
@Mohab25 | @tharanathkartoza | @Fanevanjanahary 

Apart from adding new metadata records via the Metadata Records page, one must be able to add metadata records through organisations they are a part of. In this instance, the 'Add metadata record' button is not available.

These instructions are from the Help page
![image](https://user-images.githubusercontent.com/56301949/194562514-6ee661c4-f3a9-41cd-8063-ed7bb3994ac1.png)

![adding-dataset-button-not-available](https://user-images.githubusercontent.com/56301949/194562170-dad9c245-efc6-49dc-b815-e6957ecf1bb6.gif)

**Comment by ThiashaV** [comment]
This falls under RF22 Create dataset metadata record in owned organization. @Mohab25

**Comment by gubuntu** [comment]
Where is it specified that an add metadata button is required on the organisation page? I understood that the only place to add records was to be via the Publish page. @ThiashaV @Fanevanjanahary @seabilwe 

Make absolutely sure about this sort of thing so we don't waste time on unnecessary or low priority changes. @Mohab25 did you assign this to Faneva? If so di you agree it should be done?

**Comment by seabilwe** [comment]
The 'Add metadata record' button is now available for organisation members to create metadata records
![image](https://user-images.githubusercontent.com/56301949/204246701-1beb9282-9380-4015-893e-b633092cbbf4.png)

 as stipulated in RF22
![image](https://user-images.githubusercontent.com/56301949/204246759-ab5a16c2-46e3-48a0-9102-b967740f7fbc.png)
