### ISSUE TITLE
Bad messaging about number of records

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#342]
these totals don't match - I'm logged in as admin and have no filters applied so they should surely? What are the extra two?

Total number of metadata records: 1920
1918 metadata records found

**Comment by Mohab25** [comment]
@tharanathkartoza can we run this command on the testing site, i need to see the number of records after refreshing solr, 
 `poetry run ckan search-index rebuild`

**Comment by gubuntu** [comment]
please fix urgently @Mohab25

**Comment by Mohab25** [comment]
@gubuntu fixed, the 2 extra packages came from the completed harvest jobs which get stored in the same location as packages in ckan-db

![totals](https://user-images.githubusercontent.com/58084234/198872431-546ec9fa-d136-45df-b411-3332b9804983.png)
