### ISSUE TITLE
Multiple worlds in map under search by location

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#359]
Would it be possible to make it just one world instead of 3 
![image](https://user-images.githubusercontent.com/98025261/198250793-07f01610-88f0-4ecb-b0fb-c40083aa9267.png)

**Comment by Mohab25** [comment]
@ThiashaV give it a check and close accordingly

**Comment by ThiashaV** [comment]
![image](https://user-images.githubusercontent.com/98025261/200354109-835d97e1-2e78-404f-9e6c-22987e93ea6a.png)
