### ISSUE TITLE
RF17 Manage non-owned user profile

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#362]
RF17 Manage non-owned user profile.
A user’s profile shall only be modifiable by the user or by the system administrator.

**Comment by gubuntu** [comment]
this was done and delivered early on by Ricardo, what's the issue here @ThiashaV ? 

If there's something not working, specify the problem. Otherwise this seems spurious and should be closed cc @Mohab25

**Comment by Mohab25** [comment]
@ThiashaV this is a core functionality that comes out-of-box with CKAN, unless there is something wrong with testing please go ahead and close, otherwise i would be happy to walk you through the testing process

**Comment by ThiashaV** [comment]
![image](https://user-images.githubusercontent.com/98025261/200354325-a1eab91f-20e4-4364-8b8c-487ed0a50d81.png)

**Comment by Jeremy-Prior** [comment]
Managing a non-owned user profile as the sysadmin with no issues:
![UpdatingNon-OwnedProfile](https://user-images.githubusercontent.com/100694811/204282514-690cbc34-978a-428f-ac1a-09b72ab4938a.gif)

The changes then reflect on the updated profile as though the user updated their own profile (not sure if this needs to be changes or not):
![ChangesReflected](https://user-images.githubusercontent.com/100694811/204282594-716bb4f4-fdcb-4970-96a8-e3e20e633aab.gif)
