### ISSUE TITLE
Please explain/ point to documentation: RF26 Perform bulk import of metadata records via the system CLI.

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#363]
please document this or point to existing documentation in GitHub and please post screenshots or screencasts and please explain how it can be tested.

**Comment by gubuntu** [comment]
@ThiashaV this was implemented and delivered many months ago. And your description doesn't specify a task or problem. Rather update the title and description to ask what I think you want to know and that is 'please document this or point to existing documentation in GitHub and please post screenshots or screencasts and please explain how it can be tested'

This is a task that only a superadmin can do so only one or two people (like @ntobe-nyuswa ) will be able to or need to test this
