### ISSUE TITLE
Opening the "Help" page in a new tab just re-opens the same page.

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#378]
When a user clicks on the "Help" drop down menu and then right clicks to open the "Help" page in a new tab it just loads the same page that the user was on when they tried to open the new tab. 
![1_NewIssue](https://user-images.githubusercontent.com/100694811/203744929-90e34b2c-96b7-46e3-af84-c98517d0116a.gif)

**Comment by gubuntu** [comment]
@ThiashaV @Fanevanjanahary what happened to the original Help page itself? We wanted to keep that as an introduction and index page. Also, please reorder the menu items to be more user-oriented e.g. searching and browsing first and more admin type help later.

**Comment by ThiashaV** [comment]
@gubuntu the original help page is still there. @Fanevanjanahary still needs to add it to the drop-down.

**Comment by Mohab25** [comment]
@Jeremy-Prior fixed with the new PR, re-open if you see so.

**Comment by Jeremy-Prior** [comment]
"Help" is now available in the drop-down menu so right-clicking and opening the "Help" link in a new tab is not a needed functionality:
![2_NotNeeded](https://user-images.githubusercontent.com/100694811/204991572-c839b00e-0093-45cc-a6c5-8e161915bcb9.gif)
