### ISSUE TITLE
Disable data upload and download 

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#379]
The EMC is a metadata clearinghouse only. It is not a data management platform. It is not in scope to store any data other than metadata records. Custodians or their agents are responsible for storing, managing and serving the data sets that the metadata describes. 

Metadata records on the EMC MUST include resource links, however, pointing to WMS, WFS, download or any other relevant link as per SANSA 1878, if these exist. 

So, please hide or otherwise disable the Upload button in the screen, adjust the text to refer only to links, not files, and remove the resource file download link

![Screenshot 2022-11-24 at 10 22 53](https://user-images.githubusercontent.com/496911/203730820-e16899c5-cac1-4b6b-a671-91229e2ee8db.png)

Remove 'Download' option:
![download](https://user-images.githubusercontent.com/100694811/203725329-e2214dcd-7909-46de-88a3-ebc94b7e15e1.png)

Change 'Data and Resources' to 'Links'. And change 'This dataset has no data' to 'This metadata record has no links'
![Screenshot 2022-11-28 at 14 37 14](https://user-images.githubusercontent.com/496911/204279863-699ff359-1de3-48ab-b97a-9e2208ca4c6f.png)

Change this to 'Add links':
![Screenshot 2022-11-28 at 14 39 29](https://user-images.githubusercontent.com/496911/204280004-e25160f1-5c01-4dbe-a279-7cd885fea7e8.png)

**Comment by Mohab25** [comment]
![Screenshot from 2022-11-28 19-34-09](https://user-images.githubusercontent.com/58084234/204344640-9d704671-56b3-4e79-845d-3161523ec5c6.png)
![Screenshot from 2022-11-28 19-34-48](https://user-images.githubusercontent.com/58084234/204344647-98cd8f62-1d98-43ca-b386-793042a3a426.png)
![Screenshot from 2022-11-28 19-35-12](https://user-images.githubusercontent.com/58084234/204344652-56d3a76a-182b-4d24-872e-c9e8285cac96.png)
![Screenshot from 2022-11-28 19-36-44](https://user-images.githubusercontent.com/58084234/204344657-36ec041d-0e01-4a28-9ecc-4bd15ea37ca8.png)

**Comment by Jeremy-Prior** [comment]
Data Download facility removed from testing site:
![5_DownloadDisabled](https://user-images.githubusercontent.com/100694811/204467067-92d9acce-521f-400c-8824-559fd66f1551.png)
Data Upload facility removed:
![5_NoUpload](https://user-images.githubusercontent.com/100694811/204467175-6fa18928-9cde-414f-ae57-1b33258ee5ab.png)
