### ISSUE TITLE
SANSA 1878 mandatory fields should be mandatory in CKAN

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#386]
At least one field (Acknowledgment) says its mandatory in the tip but does not have a red star. There may be others...
![Screenshot 2022-11-28 at 14 20 56](https://user-images.githubusercontent.com/496911/204276876-d5181542-e330-4875-935a-7ba3b1fbf139.png)

**Comment by Mohab25** [comment]
removed the text under acknowledgement which is not a mandatory field, add usage field to the schema
![acknowledgement](https://user-images.githubusercontent.com/58084234/204387616-d582f468-8891-4e58-981a-cb0f540ea610.png)
![specific usage](https://user-images.githubusercontent.com/58084234/204387666-bfee310d-0263-4097-badb-b95977b4c142.png)

@Jeremy-Prior @seabilwe a last round of tests would be great, reopen if there is something wrong

**Comment by Jeremy-Prior** [comment]
@Mohab25 
"Organisation role" is a mandatory field as it should be but does not have a tip:
![1_OrganisationTip](https://user-images.githubusercontent.com/100694811/204523296-25b47f66-62e9-452a-b708-b13801ba23c6.png)

"Maintainer" is correctly implemented as an optional field as per the SANS 1878 document but the tip says it is mandatory:
![6_MaintainerTip](https://user-images.githubusercontent.com/100694811/204523625-a5fe6c4b-208b-422c-8edc-a165a209f96d.png)

"Temporal Reference System Information" is correctly implemented as an optional filed but the tip says it is mandatory, I have a suggested change in the screenshot but removing the "This is partly a SANS 1878 mandatory filed" is also fine:
![7_TemporalIdentifier](https://user-images.githubusercontent.com/100694811/204524237-2b0af5d8-f638-427d-ab55-54ef36c8a4b6.png)

**Comment by Jeremy-Prior** [comment]
Changes applied on testing site.
