### ISSUE TITLE
Clicking on "Organisation Management and Membership Documentation" doesn't take you to the correct page.

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#391]
When clicking on "Organisation Management and Membership Documentation" from the "Help" drop down menu, a user is redirected to the "Pages" page:
![1_DropdownMenu](https://user-images.githubusercontent.com/100694811/204494997-da74248e-d3f4-414a-a709-e49d87b53cb7.gif)

When clicking on "Organisation Management and Membership Documentation" from the "Help" page, a user is redirected to the "Pages" page:
![2_FromHelpPage](https://user-images.githubusercontent.com/100694811/204495137-0f45667e-d4eb-42db-8c2b-c1e8896cadac.gif)

When clicking on "Organisation Management and Membership Documentation" on the "Pages" page, a user is redirected to the correct page: 
![3_FromPages](https://user-images.githubusercontent.com/100694811/204495275-3294919e-58e2-4132-a436-514d41ac89d5.gif)

**Comment by seabilwe** [comment]
You can close the ticket once you have checked

**Comment by Jeremy-Prior** [comment]
@seabilwe thank you, it's working on the testing site now:
![4_FixedFromHelp](https://user-images.githubusercontent.com/100694811/204500007-517f974c-5f0c-4676-9819-2d5f03ded0a8.gif)

As you say, just the drop-down issue now.

**Comment by Mohab25** [comment]
@Jeremy-Prior fixes with the new PR, give it a check and re-open if necessary

**Comment by Jeremy-Prior** [comment]
Fixed in the dropdown too:
![5_FixedDropdown](https://user-images.githubusercontent.com/100694811/204988879-016f10cb-8f76-4f46-be41-e2fac2247fa9.gif)
