### ISSUE TITLE
Users can search for records and they show up as public but the records link to a private record. 

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#407]
Users can search for records and they show up as public but the records link to a private record. e.g. Land Parcel record. 
Anonymous users see this record and when they click on it they get an error 404.
![image](https://user-images.githubusercontent.com/98025261/206201535-40a6ab98-a31a-43b7-adf4-d4df801eb0a5.png)
![image](https://user-images.githubusercontent.com/98025261/206201770-f5c72406-9bf7-4e60-926a-dd7c8128474c.png)
when you try access this as an admin, you see two versions of the record. one shows as private and one as public.
![image](https://user-images.githubusercontent.com/98025261/206202509-47aeaa12-f058-4a25-83cf-084763d5080d.png)
if you click on the public one it links you back to the private one
![image](https://user-images.githubusercontent.com/98025261/206202680-679a222f-49d6-4880-997b-eaf270ebf40f.png)

**Comment by Mohab25** [comment]
after latest modifications, i think this has been handled, changing the data from public to private would happen in a manual fashion via system admins, which would avoid such case.

**Comment by Jeremy-Prior** [comment]
Private records no longer show up as public records. Sysadmin account (left hand side) can see the private record while the record does not appear for an an anonymous user (right hand side):
![PrivateRecordsFixed](https://user-images.githubusercontent.com/100694811/206989997-dbe6ddaf-e328-49ba-888d-6c3426058d5b.png)
