### ISSUE TITLE
 The option to click a little 'x' to clear the filter does not appear on Organisations, SASDI Themes, etc

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#416]
On the staging site, when you apply a filter to your search (e.g. Organisations, SASDI themes, etc) the option to click a little 'x' to clear the filter does not aappear (see gif):
![filter-options do-not-show-x option](https://user-images.githubusercontent.com/56301949/208623932-57fdb340-334d-4cc4-b4c0-c195ffef6abf.gif)

It should be present as shown in the image below:

![2022-12-20_10-41](https://user-images.githubusercontent.com/56301949/208624068-5e1dd6d3-15f6-4fe9-a983-3383cc127c6c.png)

**Comment by seabilwe** [comment]
@Fanevanjanahary the 'x' icon is still not appearing when filtering the searches.
![image](https://user-images.githubusercontent.com/56301949/211283244-bd282531-d313-47cc-ae49-27f7b03cf2a0.png)

**Comment by Fanevanjanahary** [comment]
Hi @seabilwe, please can you test this?

**Comment by seabilwe** [comment]
Hi @Fanevanjanahary, it still is not showing
![filtering data](https://user-images.githubusercontent.com/56301949/211798391-dc311c9c-101f-4703-a4b3-481f939625bc.gif)

**Comment by Fanevanjanahary** [comment]
Hi, @seabilwe can you please test it on testing?

**Comment by seabilwe** [comment]
@Fanevanjanahary just checked the on the testing and it works okay
![filtering data2](https://user-images.githubusercontent.com/56301949/211813002-706a77f6-1531-464e-912f-03fac10ff275.gif)

**Comment by Jeremy-Prior** [comment]
Functionality working on staging site now:
![XOnStaging](https://user-images.githubusercontent.com/100694811/212269564-464656ce-a70a-4c63-bd0c-4e4daf58a1ff.gif)
