### ISSUE TITLE
Set up automated deployments to staging environment 

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#42]
Automate image builds on commits or merges to the main branch. 

Manually (on demand) deploy these to the staging env. 

This initially included 'automated', but automating deployment means deploying Argo on the staging environment, which will increase complexity and resource demands unnecessarily.

**Comment by gubuntu** [comment]
@Mohab25 @tharanathkartoza I've seen you discussing this on Slack, please flesh out the OP and discuss progress here

**Comment by gubuntu** [comment]
done, in operation

**Comment by Jeremy-Prior** [comment]
Per Gavin's comment:
> done, in operation
