### ISSUE TITLE
UI in dataset page 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#426]
- [x] Reduce the margin below the menu
- [x] Make pagination on the right
- [x] Move date to the bottom of card
- [x] Move label to the right side of card
- [x] Set active color of tabs differently (see figma for the color)
- [x] Set default image and border to thumbnails

**Comment by gubuntu** [comment]
@Fanevanjanahary please close this if it is indeed completed
