### ISSUE TITLE
Clicking on some of the page links causes the site to temporarily crash.

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#441]
When a user clicks on the link to the "Saved Search" and "Error Reports" pages the site crashes for a few minutes and then comes back online. If a user refreshes the https://testing.emc.kartoza.com/error_report/ page the site crashes again (crash happens on both staging and testing but staging doesn't come back online while testing does).
Example of clicking on "Error Reports" link:
![ErrorReportsCrash_1](https://user-images.githubusercontent.com/100694811/212299783-b5f15aac-99c2-4ac0-aa8f-735f8d0ec533.gif)

This is the error:
![ErrorReportsCrash_2](https://user-images.githubusercontent.com/100694811/212297556-5f5b7c4f-592b-422c-812f-3524b7d5bd98.gif)

**Comment by ThiashaV** [comment]
Clicking on the page links that previously caused the site to temporarily crash works now and the site does not crash when clicking on 'error reports' and 'saved searches'.
![image](https://user-images.githubusercontent.com/98025261/212851445-0e4867d5-827c-45ea-951f-0419601001d0.png)
![image](https://user-images.githubusercontent.com/98025261/212851548-e24709c1-4eb1-464e-9d27-791fe52d6418.png)
