### ISSUE TITLE
Rearranging 'Help' and 'FAQ' pages at Vutomi's request

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#456]
Adding new 'Contacts' page to 'Help' drop-down menu. adding "FAQ' to 'Help' drop-down menu. Renaming 'Help' menu to 'Resources'.

@seabilwe  @Fanevanjanahary

**Comment by Jeremy-Prior** [comment]
This has been implemented
![Issue456_1](https://user-images.githubusercontent.com/100694811/219344514-19558d78-dcd3-46e5-94d3-3f9d755a5488.png)
