### ISSUE TITLE
The temporal range filter, is filtering incorrect records 

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#474]
@Mohab25 

The temporal range filter filters incorrect records for a specified date range.
The calendar seems to be broken when testing on Firefox 

![ChromeCalendar](https://user-images.githubusercontent.com/56301949/216064346-d34705fa-7e38-4cca-b67a-a678074c5558.png)
![Firefox_calendar](https://user-images.githubusercontent.com/56301949/216064349-6fcb2ec2-04bf-43be-a84e-85fdef7abe5e.gif)

**Comment by gubuntu** [comment]
it is supposed to filter on the record date (the date/s represented by the data), NOT on the metadata update date

**Comment by seabilwe** [comment]
The temporal extent filter, now, filters records based on the reference date given to the record. If a record created, was not given a reference date, it will appear in all searches irrespective of the dates filtered.
