### ISSUE TITLE
Add Kartoza and CKAN reference to page footer

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#477]
Per feedback during the All Hands meeting today (03/02/2023):

- [ ] The Kartoza logo should be added to the footer of the page barring issues with government regulations and reference to using CKAN should also be added to the footer

OR

- [x] Add a text reference along the lines of "Powered by CKAN, developed by Kartoza" into the footer.

**Comment by seabilwe** [comment]
This had been added

>  Add a text reference along the lines of "Powered by CKAN, developed by Kartoza" into the footer.

![image](https://user-images.githubusercontent.com/56301949/219354410-b2b42599-ad43-4287-a4c1-7a70f8065d72.png)
