### ISSUE TITLE
Temporal Range filter breaks when a search term is applied and then a date is selected

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#483]
When an anonymous user (R1) goes to the 'Search Metadata' page, types in and applies a search term, then tries to apply a temporal range filter the temporal field remains blank. If the user then tries to select another date the site throws an error.

Video of creating error:[TemporalFilterError.webm](https://user-images.githubusercontent.com/100694811/217273651-28cdc924-9f4c-4658-af57-3e9c5bcfb7e7.webm)

The issue is replicable on Firefox, Chrome and Brave (cc @seabilwe).
The search term applied doesn't matter and the date applied after the search term also makes no difference.

**Comment by Fanevanjanahary** [comment]
Hi, @Jeremy-Prior did you test this on staging? Please can you test on testing? It's fixed

**Comment by Jeremy-Prior** [comment]
Hi @Fanevanjanahary, I tested on staging but I can replicate the same error on testing

**Comment by Jeremy-Prior** [comment]
@Fanevanjanahary 

Here is a video of making the error on testing:
[TemporalErrorOnTesting.webm](https://user-images.githubusercontent.com/100694811/217463051-f77c9858-290a-4bfc-8839-b8d66a3c9faf.webm)

**Comment by Fanevanjanahary** [comment]
I see it now, thank you @Jeremy-Prior

**Comment by Jeremy-Prior** [comment]
This is now fixed
[Fixed.webm](https://user-images.githubusercontent.com/100694811/219342468-09075bea-593a-499c-bbf4-d993cfec669f.webm)
