### ISSUE TITLE
Registered users cannot view/ search or create DCPR records (R5F3/ RF54/ RF55/RF56/ RF58/ RF59/ RF61)

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#486]
Registered users (R2) cannot create DCPR records using form E1 or E2 and as a result, they cannot view / search/ delete their own unsubmitted DCPR records.
 they cannot:

-  View and Search Owned Unsubmitted DCPR Records (RF53)

![image](https://user-images.githubusercontent.com/98025261/217529943-2662f798-85c5-4a9d-9ee7-4dbc97176f18.png)

- Create DCPR Record. (RF54) / Create DCPR Record with Contents of Form E1. (RF55) / Create DCPR Record with Contents of Form E2.(RF56)

![image](https://user-images.githubusercontent.com/98025261/217530081-69607dbc-c9f7-42c7-9c45-cc304b513464.png)

- Modify Owned Unsubmitted DCPR Record. (RF58)
-  Delete Owned Unsubmitted DCPR Record. (RF59)
- Submit Owned DCPR Record for Approval. (RF61)

@Mohab25 @Fanevanjanahary

**Comment by Jeremy-Prior** [comment]
Registered users (R2) can now create DCPR records using form E1 or E2 and they can view / search/ delete their own unsubmitted DCPR records.
- Creating Record via Form E1 as an R2 or R3 user (also works with Form E2)
![Issue486_1](https://user-images.githubusercontent.com/100694811/219341315-b20ca641-7210-4529-bfe8-6b6d63af3dce.png)
- Able to view public requests and own requests as an R2 and R3 user
![Issue486_2](https://user-images.githubusercontent.com/100694811/219341330-abde6d92-1f35-48ee-b201-3b8c9053d288.png)
