### ISSUE TITLE
improve borders and alignment

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#507]
Note how the internal borders on the left almost align and on the right there is a slight gap. Whatever you do, it should be symmetrical. Either remove the gap completely or better still add a slight gap to both sides that looks nice

![Screenshot 2023-05-04 at 09 29 46](https://user-images.githubusercontent.com/496911/236138433-bccbcf91-1722-4e03-a0d8-3b649e3e1a98.png)

**Comment by Fanevanjanahary** [comment]
This is not fixed yet

**Comment by voogt** [comment]
![image](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/assets/47378310/d73d878f-0eaf-483a-91ba-dbbb307d856e)
fixed alignment with borders
