### ISSUE TITLE
fix wording and styling

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#509]
remove 'ther'

and fix this and all other screens as per #507

![Screenshot 2023-05-04 at 10 29 13](https://user-images.githubusercontent.com/496911/236151337-ac6b0894-340b-439d-8f36-f8ef66d63a87.png)

**Comment by voogt** [comment]
this has been addressed 
![image](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/assets/47378310/7cbd8a93-cfcb-4aa9-b407-116ea8ea0baa)
