### ISSUE TITLE
Fix HTML page title on production site

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#513]
The html page title of the production site needs to be adjusted. It still says staging:
![image](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/assets/100694811/a6e47357-de44-4ebc-ba7f-e51d2fcb60a0)

**Comment by voogt** [comment]
Update ` ckan.site_title` variable in file `docker/ckan-dev-settings.ini`
