### ISSUE TITLE
Remove API Key form user profile

### ISSUE THREAD

**Issue by voogt** [kartoza/ckanext-dalrrd-emc-dcpr#545]
- Remove generation of API Key from user profile

**Comment by gubuntu** [comment]
access via the API is a requirement so there must still be a way to get a key - think about and propose a solution here and discuss with client too before implementing

**Comment by voogt** [comment]
Hi @gubuntu I'm referring to this bit here 
![image](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/assets/47378310/6594acf3-2242-4846-b7a1-982181c87df9)
If you generate an api key on your profile you are free to upload files and bypass any restrictions using ckan's api.
If I remove this bit from the profile users are still  able to upload resources to datasets but they cant use ckan's api as described in this documentation https://docs.ckan.org/en/2.9/maintaining/filestore.html#filestore-api

**Comment by voogt** [comment]
@gubuntu what was the original requirement for use of the API key?

**Comment by voogt** [comment]
Update Filestorage API security

**Comment by voogt** [comment]
file check is added for the following types to not allow upload:

- "text/html", 
- "application/java", 
- "application/java-byte-code", 
- "application/x-javascript", 
- "application/javascript", 
- "application/ecmascript", 
- "text/javascript", 
- "text/ecmascript",
- "application/octet-stream",
- "text/x-server-parsed-html",
- "text/x-server-parsed-html"

**Comment by voogt** [comment]
- Test new security updates
