### ISSUE TITLE
Add categories for each of the SASDI themes

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#57]
We need to add categories for each SASDI theme, as described in

http://www.sasdi.gov.za/sites/SASDI/Acts%20Policies%20and%20Procedures/List%20of%20appointed%20base%20data%20set%20custodians%20-%2030%20November%202020.pdf

Additionally, each new dataset should have at least one of these categories. Thus we will need to enforce this too

**Comment by vutomim** [comment]
Hi Ricardo,

Not all data set will fit on the themes. Those are only the ones we've prioritized to implement but there are as many as 41 themes that need to be implemented and we anticipate additional themes coming from the Marine and Coastal Environment. The other data set, will have to fit table 15 of SANS1878 standard.
