### ISSUE TITLE
Implement remaining SANS 1878 fields

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#84]
When creating a new metadata record we need to be able to store sufficient information to be able to support the SANS1878 metadata standard, AKA the South Africa ISO 19115 metadata profile.

This pertains to requirements:
- **RF22**
- **RF23**
- **RF24**

Refer back to the system architecture design document for more background on the SANS 1878 document and related metadata fields.

This issue is about adding support for all SANS1878 metadata fields that have not been implemented yet. 

**More information about which fields to implement shall be added soon**

More information about SANS1878 fields in the wiki:

https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/wiki/sans-1878-research#additional-elements

**Comment by gubuntu** [comment]
all SANSA 1878 fields must be supported, with appropriate validation rules (optional, allowed enumerations, thesauri etc.)

**Comment by gubuntu** [comment]
consider doing #168 at the same time

**Comment by gubuntu** [comment]
@Mohab25 was this done with #290?

**Comment by Jeremy-Prior** [comment]
@Mohab25 look at the google sheet (https://docs.google.com/spreadsheets/d/1YehY7KZkF7vgSFZzDqifbTgjZtJNXoYB-7D37YKPkAA/edit?usp=sharing) to see whether a SANS1878 category has been implemented or not. Also look at Abi's comments on the sheet.

**Comment by seabilwe** [comment]
@Mohab25 please have a look at the google sheet (https://docs.google.com/spreadsheets/d/1YehY7KZkF7vgSFZzDqifbTgjZtJNXoYB-7D37YKPkAA/edit#gid=0).

Two additional columns (Correctness of implementation status and Comments on the implementation) have been added, which describe the correctness of the implementation of the core metadata elements and additional elements. Please also take note of the additional comments made on the sheet.

**Comment by Jeremy-Prior** [comment]
Addressed in #375 from @Mohab25. Double-checked and the fields match those in the google sheet (https://docs.google.com/spreadsheets/d/1YehY7KZkF7vgSFZzDqifbTgjZtJNXoYB-7D37YKPkAA/edit#gid=0)

Only remaining issues is "Brief" being misspelt as "Breif" in the subtext of "Purpose":
![Misspelling](https://user-images.githubusercontent.com/100694811/203069415-36c88fc4-bad1-4f06-80ee-ada1a72632d0.png)

**Comment by Mohab25** [comment]
![Brief](https://user-images.githubusercontent.com/58084234/204351514-5e1c0103-fd5b-4f79-b99b-5103db9394b7.png)

**Comment by Jeremy-Prior** [comment]
Fixed on testing site:
![BriefFixed](https://user-images.githubusercontent.com/100694811/204467981-5db0138c-ce05-4c81-b804-401a01a26c5a.png)
