### ISSUE TITLE
Get acquainted with project docs and existing code

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#87]
In order to gain relevant knowledge about the project, please go through the following items:

- System Architecture Design document (version 1.0), as present on our internal platform. Most relevant sections:
  - Section _6 Technology Viewpoint_
  - _Annexure B - Production Environment requirements_
- The devops repo related to this project
- Other internal notes gotten from team members

**Comment by ricardogsilva** [comment]
@dominicschaff can I close this?

**Comment by dominicschaff** [comment]
I think yes. I have gone through those documents.
